import React, { useRef, useState } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import logo from "../assets/logo.jpg";
import watermark from "../assets/short.png";

export default function InvoiceGenerator() {
  const invoiceRef = useRef();

  const [invoiceData, setInvoiceData] = useState({
    bookingId: "",
    generatedBy: "",
    dateOfJourney: "",
    timeOfJourney: "",
    journeyEndTime: "",
    endOfJourney: "",
    tripType: "",
    pickupAddress: "",
    destination: "",
    companyName: "",
    customerName: "",
    customerPhone: "",
    customerGSTIN: "",
    baseFare: 0,
    gst: 0,
    tollCharges: 0,
    parkingCharges: 0,
    totalAmount: 0,
    roundOff: 0,
    advanceAmount: 0,
    outstandingAmount: 0,
    amountInWords: "",
    accountName: "",
    bankName: "",
    bankBranch: "",
    totalkm: 0,
    carType: "",
  });

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setInvoiceData((prev) => ({ ...prev, [name]: value }));
  };

  const generatePDF = async () => {
    if (!invoiceRef.current) return alert("Invoice content is missing!");

    const canvas = await html2canvas(invoiceRef.current, {
      scale: 2,
      useCORS: true,
    });
    const imgData = canvas.toDataURL("image/jpeg", 1.0);

    const pdf = new jsPDF("p", "mm", "a4");
    const imgProps = pdf.getImageProperties(imgData);
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

    pdf.addImage(imgData, "JPEG", 0, 0, pdfWidth, pdfHeight);
    pdf.save(`Invoice_${invoiceData.bookingId || Date.now()}.pdf`);
  };

  return (
    <div className="min-h-screen bg-gray-100 py-12">
      <div className="max-w-4xl mx-auto bg-white p-8 border shadow-lg">
        {/* ===================== INPUT FORM ===================== */}
        <div className="grid grid-cols-2 gap-2 mb-4">
          {Object.keys(invoiceData).map((field) => (
            <input
              key={field}
              name={field}
              required
              placeholder={field.replace(/([A-Z])/g, " $1").toUpperCase()}
              className="border p-2 rounded text-sm"
              value={invoiceData[field]}
              onChange={handleInputChange}
            />
          ))}
        </div>

        {/* ===================== INVOICE TEMPLATE ===================== */}
        <div
          ref={invoiceRef}
          className="px-8 py-6 p-4 relative text-[16px]"
          style={{ border: "4px solid orange " }} 
        >
          {/* Invoice Header */}
          <div className="flex justify-center items-center ">
            <div className="flex items-center">
              <img src={logo} alt="Company Logo" className="w-32" />
              <h1 className="font-bold ml-4 text-3xl">TAX INVOICE</h1>
            </div>
          </div>

          {/* Issuer & Customer Details */}
          <div className="grid grid-cols-2 gap-4 m-4">
            <div>
              <p className="font-semibold">BILL GENERATED BY :</p>
              <p>INDFLY ONROAD SERVICES  PVT. LTD.</p>
              <p className="font-semibold">GSTIN:</p>
              <p>19AAHCI7470A1ZK</p>
              <p className="font-semibold">PHONE:</p>
              <p>9330979791</p>
              <p className="font-semibold">EMAIL:</p>
              <p>
                <a
                  href="mailto:flyonroad.col@gmail.com"
                  className="text-blue-600 underline"
                >
                  flyonroad.kol@gmail.com
                </a>
              </p>
              <p className="font-semibold">WEBSITE:</p>
              <a
                href="https://flyonroad.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 underline"
              >
                flyonroad.com
              </a>
            </div>
            <div>
              <p>
                <span className="font-semibold">COMPANY NAME:</span> <br />
                {invoiceData.companyName}
              </p>
              <p>
                <span className="font-semibold">COMPANY GSTIN:</span> <br />
                {invoiceData.customerGSTIN}
              </p>
              <p>
                <span className="font-semibold">REGISTERED OFFICE:</span> <br />
                {invoiceData.pickupAddress}
              </p>
              <p>
                <span className="font-semibold">CUSTOMER NAME:</span> <br />
                {invoiceData.customerName}
              </p>
              <p>
                <span className="font-semibold">CUSTOMER PHONE:</span> <br />
                {invoiceData.customerPhone}
              </p>
            </div>
          </div>

          {/* Booking Details */}
          <div
            className="p-4 mb-4 grid grid-cols-2 gap-4"
            style={{ border: "2px solid black" }} 
          >
            <div>
              <p>
                <span className="font-semibold">BOOKING ID:</span>{" "}
                {invoiceData.bookingId}
              </p>
              <p>
                <span className="font-semibold">PICKUP DATE:</span>{" "}
                {invoiceData.dateOfJourney}
              </p>
              <p>
                <span className="font-semibold">PICKUP TIME:</span>{" "}
                {invoiceData.timeOfJourney}
              </p>
              <p>
                <span className="font-semibold">PICKUP LOCATION:</span>{" "}
                {invoiceData.pickupAddress}
              </p>
              <p>
                <span className="font-semibold">TOTAL KM:</span>{" "}
                {invoiceData.totalkm}
              </p>
            </div>
            <div>
              <p>
                <span className="font-semibold">TRIP TYPE:</span>{" "}
                {invoiceData.tripType}
              </p>
              <p>
                <span className="font-semibold">DROP DATE:</span>{" "}
                {invoiceData.endOfJourney}
              </p>
              <p>
                <span className="font-semibold">DROP TIME:</span>{" "}
                {invoiceData.journeyEndTime}
              </p>
              <p>
                <span className="font-semibold">DROP LOCATION:</span>{" "}
                {invoiceData.destination}
              </p>
              <p>
                <span className="font-semibold">CAR TYPE:</span>{" "}
                {invoiceData.carType}
              </p>
            </div>
          </div>

          {/* Watermark */}
          <img
            src={watermark}
            alt="Watermark"
            className="absolute opacity-20 left-1/3 w-80"
          />

          {/* Fare Details Table */}
          <table
            className="w-full mb-2 text-left"
            style={{ border: "2px solid black", borderCollapse: "collapse" }} 
          >
            <tbody>
              {[
                ["BASE FARE", invoiceData.baseFare],
                ["GST 5%", invoiceData.gst],
                ["TOLL & STATE TAX ", invoiceData.tollCharges],
                ["PARKING CHARGES", invoiceData.parkingCharges],
                ["TOTAL AMOUNT", invoiceData.totalAmount],
                ["ROUND OFF", invoiceData.roundOff],
                ["ADVANCE AMOUNT", invoiceData.advanceAmount],
                ["OUTSTANDING AMOUNT", invoiceData.outstandingAmount],
              ].map(([label, value]) => (
                <tr key={label}>
                  <td
                    className="p-2 font-semibold"
                    style={{ border: "1px solid black" }} 
                  >
                    {label}
                  </td>
                  <td
                    className="p-2"
                    style={{ border: "1px solid black" }}
                  >
                    INR {value}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* Amount in Words */}
          <p className="font-bold mb-4">
            AMOUNT IN WORDS: {invoiceData.amountInWords}
          </p>

          

          {/* Footer */}
          <div className="grid grid-cols-2 gap-4 mt-6">
            <div>
              <h2 className="font-bold">INVOICE ISSUED BY</h2>
              <p>INDFLY ONROAD SERVICES PVT. LTD.</p>
              <p>
                <span className="font-semibold">PAN:</span> AAHCI7470A
              </p>
              <p>
                <span className="font-semibold">HSN/SAC CODE:</span> 998551
              </p>
              <p>
                <span className="font-semibold">CIN:</span>{" "}
                U52290WB2024PTC271842
              </p>
              <p>
                <span className="font-semibold">GSTIN:</span> 19AAHCI7470A1ZK
              </p>
            </div>
            <div>
              <h2 className="font-bold">SERVICE DETAILS</h2>
              <p>Reservation Service for Transportation</p>
              <p className="mt-2">
                <span className="font-medium">REGISTERED OFFICE:</span>
                <br />
                43/8G Biplabi Barin Ghosh Sarani
                <br />
                Kolkata - 700067, West Bengal, India
              </p>
            </div>
            
          </div>
           <p className="italic flex justify-center " style={{  color: '#ff5c00' }}>
            This is a computer-generated invoice and does not require a physical signature.
          </p>
        </div>

        {/* ===================== DOWNLOAD BUTTON ===================== */}
        <button
          onClick={generatePDF}
          className="mt-6 px-6 py-3 bg-blue-600 text-white rounded hover:bg-blue-700"
        >
          Download PDF
        </button>
      </div>
     
    </div>
  );
}
